#Name: Brian Tagle
#Email: taglebrian@gmail.com
#ID: 604907076

.SILENT:

lab1a: lab1a.c
	gcc -Wall -Wextra -g lab1a.c -o lab1a
clean:
	rm -rf lab1a lab1a-604907076.tar.gz
dist:
	tar -czf lab1a-604907076.tar.gz lab1a.c Makefile README
