#NAME: Brian Tagle
#EMAIL: taglebrian@gmail.com
#ID: 604907076
.SILENT:

default:
	gcc -Wall -Wextra lab3a.c -o lab3a

dist:
	tar -czf lab3a-604907076.tar.gz Makefile README lab3a.c ext2_fs.h
clean:
	rm -f lab3a-604907076.tar.gz
