#NAME: Brian Tagle
#EMAIL: taglebrian@gmail.com
#ID: 604907076
.SILENT:

lab4a:

clean:
	rm -rf lab4a-604907076.tar.gz
dist:
	tar -czf lab4a-604907076.tar.gz Makefile README my_beaglebone.jpg connected.png copy.png build_run.png git.png
